// layout action
export const LOGMODOPEN ='LOGMODOPEN';
export const LOGMODCLOSE ='LOGMODCLOSE';
export const REGUSEROPEN ='REGUSEROPEN';
export const REGUSERCLOSE ='REGUSERCLOSE';
export const REGUSERINLOG ='REGUSERINLOG';
export const IS_USERLOGIN ='IS_USERLOGIN';
export const USER_LOGOUT ='USER_LOGOUT';
export const USER_LOGIN ='USER_LOGIN';
export const USER_START_LOGIN ='USER_START_LOGIN';
export const UPDATE_CURRENTUSER ='UPDATE_CURRENTUSER'


// card action
export const  UPDATE_WISHLIST = 'UPDATE_WISHLIST';
export const  UPDATE_CART = 'UPDATE_CART';
export const GET_NO_OF_WISHITEM ='GET_NO_OF_WISHITEM'
// sankBarAcc
export const SET_SNAKBAR = 'SET_SNAKBAR';
export const ALERT_DILOG_OPEN ='ALERT_DILOG_OPEN';
export const ALERT_DILOG_CLOSE ='ALERT_DILOG_CLOSE';


